Add Terraform module code style guide
cloudeteer/terraform-governance pull request #39
Opened 2024-09-17 12:24 UTC by rswrz

This PR introduces a code style guide for Terraform modules developed at @cloudeteer. The goal of this document is to provide consistent guidelines for writing and maintaining Terraform code across projects.

> [!IMPORTANT]
> This document is intended to serve as a starting point for discussion. We encourage team collaboration to review, suggest changes, and refine the guide before any approval or merge into the main branch.

2024-09-18 10:58 UTC, lixhunter requested changes
also add sections for

- ignore changes
- Dynamic Blocks
- Logic Style

2024-09-18 10:58 UTC, lixhunter commented on docs/Development - Terraform Style Guide.md
> +
````suggestion
### Recommended resource argument order

```hcl
resource "" {
  count

  for_each

  provider

  # other blocks sort alphabetially

  tags

  depends_on

  lifecycle
}
```

````

2024-09-18 13:43 UTC, rswrz commented
@lixhunter, done! Please review again.

2024-09-24 09:14 UTC, lixhunter approved these changes

2024-09-26 11:08 UTC, neonwhiskers submitted a review, later dismissed

2024-09-26 11:30 UTC, Phil-Thoennissen approved these changes

2024-09-27 06:00 UTC, merged