Add module review guide
cloudeteer/terraform-governance pull request #47
Opened 2024-10-01 07:22 UTC by rswrz

2024-10-08 12:06 UTC, neonwhiskers approved these changes
LGTM :)

2024-10-08 12:42 UTC, lixhunter requested changes

2024-10-08 12:42 UTC, lixhunter commented on docs/Module - Review.md
> +  - Validate that `data.tf` and `main.tf` are used, or alternatively, `d-*.tf` and `r-*.tf`.
```suggestion
  - Validate that `main.tf` is used, or alternatively, `d-*.tf` and `r-*.tf`.
```

2024-10-08 12:42 UTC, lixhunter commented on docs/Module - Review.md
> +  - Review HCL labels for clarity and descriptiveness.
```suggestion
  - Review [HCL labels](https://developer.hashicorp.com/terraform/language#about-the-terraform-language) (Name of Azure Resource) for clarity and descriptiveness.
```

2024-10-11 10:35 UTC, lixhunter approved these changes

2024-10-11 10:35 UTC, merged